### ISSUE TITLE
Events publicizing produces ambiguous reference

### ISSUE THREAD

**Issue by Sl4vP0weR** [krafs/Publicizer#110] opened 2024-06-23 12:06 UTC
When publicizing the whole assembly, I notice that events are duplicated as fields, and I'm unable to compile my project due to ambiguous reference.
Excluding used events from the process of publicizing fixes the problem.
![image](https://github.com/krafs/Publicizer/assets/42337892/c076e7ee-fcdd-4293-91c6-e8b7944b9cd7)

**Comment by krafs** [comment] 2024-06-23 12:17
This is a known possible issue, where the backing field of the event also becomes public and creates the conflict you're seeing. Did you have any luck using `IncludeCompilerGeneratedMembers=false` (see [here](https://github.com/krafs/Publicizer?tab=readme-ov-file#compiler-generated-member-name-conflicts)), or explicitly excluding the troublesome members with `DoNotPublizice`-items?

**Comment by krafs** [comment] 2024-06-23 12:32
Great! There's unfortunately no automatic fix for this, so manually excluding the cause of the conflict is the way to go. Glad you got it working 👍

**Closed** 2024-06-23 12:32 UTC
Labels: question
